name: Сборка Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Проверка кода
      uses: actions/checkout@v4

    - name: Установка Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Установка зависимостей
      run: |
        pip install pandas openpyxl python-docx

    - name: Сборка EXE (Договоры)
      run: |
        pyinstaller --onefile --windowed генератор.py

    - name: Сборка EXE (Согласия)
      run: |
        pyinstaller --onefile --windowed генератор_согласий.py

    - name: Загрузка EXE (Договоры)
      uses: actions/upload-artifact@v4
      with:
        name: Генератор-договоров
        path: dist/генератор.exe

    - name: Загрузка EXE (Согласия)
      uses: actions/upload-artifact@v4
      with:
        name: Генератор-согласий
        path: dist/генератор_согласий.exe
